# Generated by Django 5.2 on 2025-04-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0003_subscription_groups'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
