# Generated by Django 5.2 on 2025-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0004_subscription_permission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advanced', 'pro', 'basic', 'basic_ai'], 'content_type__app_label': 'Subscription'}, to='auth.permission'),
        ),
    ]
