# Generated by Django 5.2 on 2025-04-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0013_subscriptionprice_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionprice',
            name='features',
        ),
    ]
