# Generated by Django 5.2 on 2025-04-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0015_subscription_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
