# Generated by Django 5.2 on 2025-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0017_alter_subscription_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('advanced', 'Advanced Perm'), ('pro', 'Pro Perm'), ('basic', 'Basic Perm'), ('basic_ai', 'Basic AI permission')]},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='cancel_at_period_end',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='current_period_start',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='original_period_start',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user_cancelled',
        ),
        migrations.AddField(
            model_name='subscription',
            name='permission',
            field=models.ManyToManyField(limit_choices_to={'codename__in': ['advanced', 'pro', 'basic', 'basic_ai'], 'content_type__app_label': 'Subscription'}, to='auth.permission'),
        ),
    ]
