# Generated by Django 5.2 on 2025-04-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscription', '0018_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='user_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
