# Generated by Django 5.2 on 2025-04-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscount',
            name='user_count',
        ),
        migrations.AddField(
            model_name='userscount',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
