# Generated by Django 5.2 on 2025-04-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_userscount_user_count_userscount_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscount',
            name='counter',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
